[workspace]
resolver = "2"
members = ["crates/ddc-dex", "crates/ddc-dec", "crates/ddc-cli"]

[workspace.package]
version = "0.1.10"
edition = "2021"
license = "MIT"
repository = "https://github.com/ejfkdev/ddc"
homepage = "https://github.com/ejfkdev/ddc"
readme = "README.md"
keywords = ["decompiler", "dex", "dalvik", "android", "reverse-engineering"]
categories = ["command-line-utilities", "development-tools::debugging"]

[workspace.dependencies]
ddc-dex = { path = "crates/ddc-dex", version = "0.2.0" }
ddc-dec = { path = "crates/ddc-dec", version = "0.1.10" }
jdc-core = "0.2.4"
anyhow = "1"

[profile.release]
debug = true
lto = "fat"
codegen-units = 1


